### REST API Examples
### Используйте этот файл в VS Code с расширением REST Client

@baseUrl = http://localhost:8080/api/v1
@userId = 00000000-0000-0000-0000-000000000001

### Health Check
GET http://localhost:8080/healthz

###

### 1. Получить список игр
GET {{baseUrl}}/games
X-User-ID: {{userId}}

###

### 2. Создать новую игру
POST {{baseUrl}}/games
X-User-ID: {{userId}}
Content-Type: application/json

{
  "name": "Valorant"
}

###

### 3. Получить реплеи игры (Counter-Strike 2)
GET {{baseUrl}}/games/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/replays?limit=10
X-User-ID: {{userId}}

###

### 4. Получить реплеи игры (Dota 2)
GET {{baseUrl}}/games/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb/replays?limit=10
X-User-ID: {{userId}}

###

### 5. Получить детали реплея
GET {{baseUrl}}/replays/10000000-0000-0000-0000-000000000001
X-User-ID: {{userId}}

###

### 6. Загрузить реплей (замените путь к файлу)
POST {{baseUrl}}/games/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/replays
X-User-ID: {{userId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="title"

My awesome replay
------WebKitFormBoundary
Content-Disposition: form-data; name="comment"

This was an epic game!
------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="replay.rep"
Content-Type: application/octet-stream

< ./test-file.txt
------WebKitFormBoundary--

###

### 7. Обновить реплей
PUT {{baseUrl}}/replays/10000000-0000-0000-0000-000000000001
X-User-ID: {{userId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="title"

Updated title
------WebKitFormBoundary
Content-Disposition: form-data; name="comment"

Updated comment
------WebKitFormBoundary--

###

### 8. Скачать файл реплея
GET {{baseUrl}}/replays/10000000-0000-0000-0000-000000000001/file
X-User-ID: {{userId}}

###

### 9. Удалить реплей
DELETE {{baseUrl}}/replays/10000000-0000-0000-0000-000000000001
X-User-ID: {{userId}}

###

### 10. Удалить игру (и все её реплеи)
DELETE {{baseUrl}}/games/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
X-User-ID: {{userId}}

###
